### ISSUE TITLE
Backend trying to use sqlite when configured to use postgreSQL

### ISSUE THREAD

**Issue by ArchdukeNavaron** [intuitem/ciso-assistant-community#1147]
**Describe the bug**
After upgrading ciso-assistant, it cannot start and connect to postgreSQL because it tries to use SQLite (even when it is configured to use postgreSQL).

**To Reproduce**
1. Upgrade to at least ciso-assistant 1.9.18

**Environment (please complete the following information):**
- Kubernetes Version: v1.31.1

**Additional context**

**Deployment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: ciso-assistant
  name: ciso-assistant-backend
  namespace: ciso-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: ciso-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: ciso-assistant
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: backend
          env:
            - name: ALLOWED_HOSTS
              value: ciso-assistant.example.com,ciso-assistant-backend
            - name: LOCAL_STORAGE_DIRECTORY
              value: /code/data
            - name: CISO_ASSISTANT_URL
              value: https://ciso-assistant.example.com
            - name: DJANGO_DEBUG
              value: "false"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ciso-assistant-db-app
                  key: host
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: ciso-assistant-db-app
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ciso-assistant-db-app
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ciso-assistant-db-app
                  key: username
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ciso-assistant
                  key: django_secret_key
          image: ghcr.io/intuitem/ciso-assistant-community/backend:v1.9.18
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: 2G
            limits:
              memory: 2G
          volumeMounts:
            - mountPath: /code/data
              name: data
            - mountPath: /tmp
              name: tmp
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8000
              name: http-backend
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ciso-assistant-data
        - name: tmp
          persistentVolumeClaim:
            claimName: ciso-assistant-tmp
```

**Log:**

```log
2024-12-06T10:26:36.628460Z [info     ] BASE_DIR: /code                [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.628643Z [info     ] VERSION: v1.9.19               [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.628758Z [info     ] BUILD: 60f54950                [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.629129Z [info     ] DEBUG mode: False              [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.629254Z [info     ] CISO_ASSISTANT_URL: https://ciso-assistant.example.com [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.629357Z [info     ] ALLOWED_HOSTS: ['ciso-assistant.example.com', 'ciso-assistant-backend'] [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
2024-12-06T10:26:36.629551Z [info     ] DATABASE ENGINE: django.db.backends.postgresql_psycopg2 [ciso_assistant.settings] ciso_assistant_url=https://ciso-assistant.example.com
Traceback (most recent call last):
  File "/code/manage.py", line 23, in <module>
    main()
  File "/code/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/code/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/code/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/code/.venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/code/.venv/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/.venv/lib/python3.11/site-packages/huey/contrib/djhuey/__init__.py", line 101, in <module>
    HUEY = backend_cls(name, **huey_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/api.py", line 119, in __init__
    self.storage = self.create_storage()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/api.py", line 144, in create_storage
    return self.get_storage(**self.storage_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/api.py", line 156, in get_storage
    return Storage(self.name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 713, in __init__
    super(SqliteStorage, self).__init__(name)
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 628, in __init__
    self.initialize_schema()
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 664, in initialize_schema
    with self.db(commit=True, close=True) as curs:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 647, in db
    conn = self.conn
           ^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 639, in conn
    self._state.set_connection(self._create_connection())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/huey/storage.py", line 716, in _create_connection
    conn = sqlite3.connect(self.filename, timeout=self._timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
database not ready; waiting
```

**Comment by ArchdukeNavaron** [comment]
Updating to 1.9.19 didn't solve the issue

**Comment by ab-smith** [comment]
Hi @ArchdukeNavaron, today's release should fix this. Let me know.

**Comment by ArchdukeNavaron** [comment]
@ab-smith, 1.9.22 fixed the issue. Thanks!
