### ISSUE TITLE
Frontend error on last update (1.6.2)

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#679]
**Describe the bug**
Hello,
I have updated CISO Assistant to 1.6.2 from 1.6.1 and I got an error when I try to access to now.

Got 502 Bad Gateway on my client side.

Frontend log
```shell
Listening on 0.0.0.0:3000
TypeError: fetch failed
    at node:internal/deps/undici/undici:12500:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateUserSession (file:///app/build/server/chunks/hooks.server-DNnURk1b.js:29:15)
    at async Object.handle (file:///app/build/server/chunks/hooks.server-DNnURk1b.js:53:16)
    at async respond (file:///app/build/server/index.js:3354:22)
    at async Array.ssr (file:///app/build/handler.js:1261:3) {
  [cause]: Error: connect ECONNREFUSED 172.19.0.2:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.19.0.2',
    port: 8000
  }
}
```
Backend probably not handling frontend request but this is weird because I see request on backend logs
```shell
2024-07-22T07:13:12.781063Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/get_counters/ request_id=e00e5f57-08cf-4adf-856a-6d3b278a5641 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:12.791891Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/risk-matrices/used/ request_id=ce41eb17-7494-48ae-8da1-1ecea4325f52 user_agent=node user_id=None
2024-07-22T07:13:12.949390Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/risk-matrices/used/ request_id=ce41eb17-7494-48ae-8da1-1ecea4325f52 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:12.959178Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/frameworks/used/ request_id=bcbde904-2de3-440e-84d6-ba84f0c231ea user_agent=node user_id=None
2024-07-22T07:13:13.146559Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/frameworks/used/ request_id=bcbde904-2de3-440e-84d6-ba84f0c231ea user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:13.167015Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/risk-scenarios/count_per_level/ request_id=c96b7d43-5bad-472c-8156-37dcb394b910 user_agent=node user_id=None
2024-07-22T07:13:13.672902Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/risk-scenarios/count_per_level/ request_id=c96b7d43-5bad-472c-8156-37dcb394b910 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:13.683380Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/threats/threats_count/ request_id=880e8614-ccc5-42f6-b1ed-e0d0941b8f90 user_agent=node user_id=None
2024-07-22T07:13:14.592715Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/threats/threats_count/ request_id=880e8614-ccc5-42f6-b1ed-e0d0941b8f90 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:14.607389Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/applied-controls/to_review/ request_id=45974e5c-ad95-4505-b64f-32bbeb7e5206 user_agent=node user_id=None
2024-07-22T07:13:14.714694Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/applied-controls/to_review/ request_id=45974e5c-ad95-4505-b64f-32bbeb7e5206 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:14.724214Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/risk-acceptances/to_review/ request_id=8aa08f25-7539-4f06-8f1b-bc6f5a5e1e72 user_agent=node user_id=None
2024-07-22T07:13:14.819294Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/risk-acceptances/to_review/ request_id=8aa08f25-7539-4f06-8f1b-bc6f5a5e1e72 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:14.828299Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/risk-assessments/ request_id=b8eceaeb-b9ea-42d4-a78c-d7ce97dc01cb user_agent=node user_id=None
2024-07-22T07:13:14.984098Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/risk-assessments/ request_id=b8eceaeb-b9ea-42d4-a78c-d7ce97dc01cb user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:14.994284Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/projects/ request_id=3581b30f-1a28-457d-a554-f03926df4378 user_agent=node user_id=None
2024-07-22T07:13:15.115641Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/projects/ request_id=3581b30f-1a28-457d-a554-f03926df4378 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.130312Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/?project=9be5176b-bec8-47b3-970c-e09a6dc82f4e request_id=ec0a7e0c-2300-4fd2-9bca-666e8011cc5c user_agent=node user_id=None
2024-07-22T07:13:15.254456Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/?project=9be5176b-bec8-47b3-970c-e09a6dc82f4e request_id=ec0a7e0c-2300-4fd2-9bca-666e8011cc5c user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.268367Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/?project=52db4e45-a030-4bb1-8cd3-af5778b573cc request_id=003b44a3-4c2a-44e0-98b1-9c6734a908d6 user_agent=node user_id=None
2024-07-22T07:13:15.437726Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/?project=52db4e45-a030-4bb1-8cd3-af5778b573cc request_id=003b44a3-4c2a-44e0-98b1-9c6734a908d6 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.445648Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/?project=f9c0dfc7-1cec-46a2-97f1-1282226f7230 request_id=709d001f-0af9-4c00-a359-5ae663b98cb6 user_agent=node user_id=None
2024-07-22T07:13:15.560777Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/?project=f9c0dfc7-1cec-46a2-97f1-1282226f7230 request_id=709d001f-0af9-4c00-a359-5ae663b98cb6 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.564355Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/?project=ac9d5e6c-5b99-4bae-8cc2-9328349fd16b request_id=f917b6b9-c68c-4873-b3d2-26976d872f8c user_agent=node user_id=None
2024-07-22T07:13:15.713968Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/?project=ac9d5e6c-5b99-4bae-8cc2-9328349fd16b request_id=f917b6b9-c68c-4873-b3d2-26976d872f8c user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.717451Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/6a7f79d2-e8c7-4db0-8e65-011366e781b9/donut_data/ request_id=f0751313-b761-484b-bed2-8c090e615ef0 user_agent=node user_id=None
2024-07-22T07:13:15.805520Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/6a7f79d2-e8c7-4db0-8e65-011366e781b9/donut_data/ request_id=f0751313-b761-484b-bed2-8c090e615ef0 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.810339Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/6a7f79d2-e8c7-4db0-8e65-011366e781b9/global_score/ request_id=98eb0a1e-6b8f-46e6-b634-e03ddce81d23 user_agent=node user_id=None
2024-07-22T07:13:15.923648Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/6a7f79d2-e8c7-4db0-8e65-011366e781b9/global_score/ request_id=98eb0a1e-6b8f-46e6-b634-e03ddce81d23 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:15.928537Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/34214a4a-9ede-4ec1-a49e-16493395bd5e/global_score/ request_id=c2d8933c-29c4-476a-8883-6b72ff679b4b user_agent=node user_id=None
2024-07-22T07:13:16.044692Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/34214a4a-9ede-4ec1-a49e-16493395bd5e/global_score/ request_id=c2d8933c-29c4-476a-8883-6b72ff679b4b user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:16.048099Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/34214a4a-9ede-4ec1-a49e-16493395bd5e/donut_data/ request_id=25ea37a7-4576-4995-814f-8d7e951d9a13 user_agent=node user_id=None
2024-07-22T07:13:16.138500Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/34214a4a-9ede-4ec1-a49e-16493395bd5e/donut_data/ request_id=25ea37a7-4576-4995-814f-8d7e951d9a13 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:16.142148Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/ebecd3de-b5a7-4145-9afa-e9dbd103acda/donut_data/ request_id=109ef157-832a-47c3-b243-a9943464a4ab user_agent=node user_id=None
2024-07-22T07:13:16.247744Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/ebecd3de-b5a7-4145-9afa-e9dbd103acda/donut_data/ request_id=109ef157-832a-47c3-b243-a9943464a4ab user_id=4194dd0e-7645-4671-a86d-2e5894caab29
2024-07-22T07:13:16.251512Z [info     ] request_started                [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com ip=172.19.0.4 request=GET /api/compliance-assessments/ebecd3de-b5a7-4145-9afa-e9dbd103acda/global_score/ request_id=21159d44-741f-48b1-a71d-0e19b8ab9421 user_agent=node user_id=None
2024-07-22T07:13:16.375742Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.hq.gls-france.com code=200 ip=172.19.0.4 request=GET /api/compliance-assessments/ebecd3de-b5a7-4145-9afa-e9dbd103acda/global_score/ request_id=21159d44-741f-48b1-a71d-0e19b8ab9421 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
```

**To Reproduce**
1. Update image
2. Stop old docker image
3. Start new docker image
4. See error (502 Bad Gateway)

**Expected behavior**
Access to CISO Assistant login page

**Environment (please complete the following information):**
 - Device: VM
 - OS: Debian 12
 - Browser: Firefox and Edge
 - Version: Latest for both

**Additional context**
Not my reverse proxy malfunctioning because 1.6.1 before update works.

**Comment by EvoXCX** [comment]
Closing the issue, CISO Assistant decided to work in the middle of the night ^^
Idk why maybe a database migration who take longer than planned.

**Comment by ab-smith** [comment]
thanks for the feedback @EvoXCX  we will try to reproduce it as well, in case it's hiding some performance challenges
